## Configuration for the training, evaluation
samples:
  - name: RPV_1400
    label: 1
    path: ../data/trackpt_hdf5_32PU_224x224/RPV/Gluino1400GeV/*.h5
    xsec: 0.0252977
    ngen: 330599
  - name: QCD_HT700to1000
    label: 0
    path: ../data/trackpt_hdf5_32PU_224x224/QCD/HT700to1000/*.h5
    ignore: true
    xsec: 6831
    ngen: 0
  - name: QCD_HT1000to1500
    label: 0
    path: ../data/trackpt_hdf5_32PU_224x224/QCDBkg/HT1000to1500/*.h5
    xsec: 1207
    ngen: 15466225
  - name: QCD_HT1500to2000
    label: 0
    path: ../data/trackpt_hdf5_32PU_224x224/QCDBkg/HT1500to2000/*.h5
    xsec: 119.9
    ngen: 3368613
  - name: QCD_HT2000toInf
    label: 0
    path: ../data/trackpt_hdf5_32PU_224x224/QCDBkg/HT2000toInf/*.h5
    xsec: 25.24
    ngen: 3250016
training:
    randomSeed1: 123456
    nDataLoaders: 4

